apiVersion: v1
kind: Namespace
metadata:
  name: travel-agent
  labels:
    name: travel-agent
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: travel-agent-quota
  namespace: travel-agent
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: travel-agent-limits
  namespace: travel-agent
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container