# Note: This is a template. In production, create secrets using kubectl or external secret management
apiVersion: v1
kind: Secret
metadata:
  name: travel-agent-secrets
  namespace: travel-agent
type: Opaque
stringData:
  # Database
  DATABASE_URL: "postgresql://username:password@postgres:5432/travel_agent"
  
  # JWT
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
  JWT_REFRESH_SECRET: "your-super-secret-refresh-jwt-key-change-this-in-production"
  
  # Encryption Keys
  PII_ENCRYPTION_KEY: "your-32-character-encryption-key-for-pii-data"
  SESSION_ENCRYPTION_KEY: "your-32-character-session-encryption-key"
  
  # Redis
  REDIS_URL: "redis://redis:6379"
  REDIS_PASSWORD: ""
  
  # Stripe
  STRIPE_SECRET_KEY: "sk_live_your_stripe_secret_key"
  STRIPE_PUBLISHABLE_KEY: "pk_live_your_stripe_publishable_key"
  STRIPE_WEBHOOK_SECRET: "whsec_your_webhook_secret"
  STRIPE_PREMIUM_PRICE_ID: "price_premium_plan_id"
  STRIPE_PRO_PRICE_ID: "price_pro_plan_id"
  
  # PayPal
  PAYPAL_CLIENT_ID: "your_paypal_client_id"
  PAYPAL_CLIENT_SECRET: "your_paypal_client_secret"
  PAYPAL_ENVIRONMENT: "live"
  
  # Email Service
  EMAIL_SERVICE: "sendgrid"
  SENDGRID_API_KEY: "your_sendgrid_api_key"
  FROM_EMAIL: "noreply@travel-agent.com"
  FROM_NAME: "AI Travel Planner"
  
  # SMS Service
  TWILIO_ACCOUNT_SID: "your_twilio_account_sid"
  TWILIO_AUTH_TOKEN: "your_twilio_auth_token"
  TWILIO_PHONE_NUMBER: "+1234567890"
  
  # External APIs
  AMADEUS_API_KEY: "your_amadeus_api_key"
  AMADEUS_API_SECRET: "your_amadeus_api_secret"
  BOOKING_API_KEY: "your_booking_com_api_key"
  GOOGLE_MAPS_API_KEY: "your_google_maps_api_key"
  OPENAI_API_KEY: "your_openai_api_key"
  SKYSCANNER_API_KEY: "your_skyscanner_api_key"
  KIWI_API_KEY: "your_kiwi_api_key"
  
  # Health Data Integration
  FITBIT_CLIENT_ID: "your_fitbit_client_id"
  FITBIT_CLIENT_SECRET: "your_fitbit_client_secret"
  APPLE_HEALTH_KEY_ID: "your_apple_health_key_id"
  GOOGLE_FIT_CLIENT_ID: "your_google_fit_client_id"
  
  # AWS
  AWS_ACCESS_KEY_ID: "your_aws_access_key"
  AWS_SECRET_ACCESS_KEY: "your_aws_secret_key"
  AWS_BACKUP_BUCKET: "your-backup-bucket"
  
  # Error Reporting
  SENTRY_DSN: "your_sentry_dsn"
  
  # Admin
  ADMIN_EMAIL: "admin@travel-agent.com"
  SECURITY_ALERTS_EMAIL: "security@travel-agent.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: travel-agent
type: Opaque
stringData:
  POSTGRES_DB: "travel_agent"
  POSTGRES_USER: "travel_agent_user"
  POSTGRES_PASSWORD: "secure_password_change_in_production"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: travel-agent
type: Opaque
stringData:
  REDIS_PASSWORD: "secure_redis_password_change_in_production"